version: '3.8'

services:
  app:
    build: .
    ports:
      - '${PORT:-3333}:${PORT:-3333}'
    depends_on:
      - db
      - redis
    env_file:
      - .env
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379

  db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: task_js
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - '6379:6379'

volumes:
  pgdata:
